include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
  language:
      strict-inference: true

linter:
  rules:
    - camel_case_types